GET http://localhost:5000/api/products/1

###
GET http://localhost:5000/api/users/test-user-id

###
GET http://localhost:5000/api/products

###
GET http://localhost:5000/api/products/search/?text=rest&min=10&max=100

###
GET http://localhost:5000/api/products/search/?text=0&max=50

###
GET http://localhost:5000/api/products/search/?text=&max=asd